server:
  port: 4000
  env: "development" # <-- ✅ ДОБАВЬТЕ ЭТУ СТРОКУ (или "production")

database:
  driver: "postgres"
  url: "postgres://postgres:Sagster-2020@localhost:5432/mwork?sslmode=disable"

